# Generated by Django 2.1.7 on 2019-03-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='supply',
            name='state',
            field=models.TextField(default=''),
        ),
    ]
