# Generated by Django 2.1.7 on 2019-05-23 14:04

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_auto_20190323_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='image',
            field=models.ImageField(default='', storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=''),
        ),
    ]
