# Generated by Django 2.1.7 on 2019-05-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_auto_20190323_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='last_time_scanned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supply',
            name='to_be_scanned',
            field=models.BooleanField(default=True),
        ),
    ]
