# Generated by Django 2.1.7 on 2019-05-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_auto_20190514_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='last_time_scanned',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
