# Generated by Django 2.1.7 on 2019-06-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_supply_deleted'),
        ('supplies', '0005_auto_20190514_2036'),
    ]

    operations = [
    ]
