# Generated by Django 2.1.7 on 2019-06-27 16:05

from django.db import migrations, models
import supplies.validators


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0007_auto_20190627_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='repletion',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[supplies.validators.validate_repletion]),
        ),
    ]
