# Generated by Django 2.1.7 on 2019-04-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0003_auto_20190408_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printqueue',
            old_name='supplyId',
            new_name='supply',
        ),
    ]
