# Generated by Django 2.1.7 on 2019-04-11 20:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplies', '0002_auto_20190323_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InventorySupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False)),
                ('inventory_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_supplies', to='inventories.InventoryReport')),
                ('inventory_supply', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supplies.Supply')),
            ],
        ),
    ]
