# Generated by Django 2.1.7 on 2019-04-14 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorysupply',
            name='inventory_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_supplies', to='inventories.InventoryReport'),
        ),
        migrations.AlterField(
            model_name='inventorysupply',
            name='inventory_supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.Supply'),
        ),
    ]
