# Generated by Django 2.1.7 on 2019-05-05 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0002_auto_20190414_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorysupply',
            name='inventory_supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.Supply'),
        ),
    ]
