# Generated by Django 2.1.7 on 2019-05-23 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0002_auto_20190414_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreport',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
